#!/usr/bin/env bash
# Script that configures Nginx to run as nginx user and listen on port 8080
sudo chmod -R 755 /etc/nginx/
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
su nginx -c "service nginx restart"

