#!/usr/bin/env bash
# Script that configures Nginx to run as nginx user and listen on port 8080

id -u nginx &>/dev/null || useradd -r -s /bin/false nginx

sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80/listen \[::\]:8080/g' /etc/nginx/sites-available/default

chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/nginx

pkill -f nginx
nginx

