#!/usr/bin/env bash
#A script that fixes Apache and provides a Hello Holberton page

apt-get update -y
apt-get install -y apache2
service apache2 start
echo "Hello Holberton" > /var/www/html/index.html

