#!/usr/bin/env bash
# Script that configures Nginx with custom HTTP response header
# shellcheck disable=SC2154

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html

cat > /etc/nginx/sites-available/default <<EOF
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	# Add custom header with hostname
	add_header X-Served-By \$hostname;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	location / {
		try_files \$uri \$uri/ =404;
	}
}
EOF

service nginx restart
