#!/usr/bin/env bash
# Script that installs and configures HAProxy load balancer


apt-get update -y
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

cat > /etc/haproxy/haproxy.cfg << 'EOF'
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 6805-web-01 check
    server 6805-web-02 check
EOF

service haproxy restart