#!/usr/bin/env bash
#Script that installs Nginx, stops conflicting services, and starts Nginx on port 80

sudo apt-get update -y
sudo apt-get install -y nginx

sudo if service apache2 status > /dev/null 2>&1; then
    service apache2 stop
fi

sudo service nginx start

