#!/usr/bin/env bash
#Script that installs Nginx, stops conflicting services, and starts Nginx on port 80

apt-get update -y
apt-get install -y nginx

if service apache2 status > /dev/null 2>&1; then
    service apache2 stop
fi

service nginx start

