#!/usr/bin/env bash
# Script that installs Nginx, stops conflicting services, and starts Nginx on port 80

if service apache2 status > /dev/null 2>&1; then
    service apache2 stop
fi

apt-get update -y
apt-get install -y nginx

mkdir -p /var/www/html
echo "Hello Holberton" > /var/www/html/index.html

nginx -g "daemon off;" &

