#!/usr/bin/env bash
# Script that fixes nginx to listen on port 80 in a container
apt-get update -y
apt-get install -y nginx
sed -i 's/listen 80 default_server/listen 80/' /etc/nginx/sites-enabled/default
