#!/usr/bin/env bash
# Script that installs and configures nginx to serve a page containing 'Holberton School'

apt-get update -y
apt-get install -y nginx
service nginx start
echo "Holberton School" > /var/www/html/index.html
service nginx restart

