#!/usr/bin/env bash
# Script that installs and configures nginx to serve a page containing 'Holberton School'

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School " > /var/www/html/index.html
sudo service nginx start
