#!/usr/bin/env bash
# Script that configures Nginx to serve "Holberton School" and redirect /redirect_me

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html

cat > /etc/nginx/sites-available/default <<'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/;
    }
}
EOF

nginx -t
service nginx restart

